name: Issue Response

on:
  issues:
    types: [opened]

jobs:
  issue-response:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Thank user and add label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const issueAuthor = context.payload.issue.user.login;

            // Add comment thanking the user
            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Hello @${issueAuthor}!

Thank you for raising this issue! Our team will review it as soon as possible.

Please make sure you've included:
- A clear description of the problem
- Steps to reproduce (if applicable)
- Expected behavior
- Current behavior

We appreciate your contribution to making Travel Planner better!`
            });

            // Add "triage" label to the issue
            await github.rest.issues.addLabels({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage']
            });
